import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SearchBar from './components/SearchBar'
import useSWR from "swr";

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  const { data, error } = useSWR(
    "https://api.github.com/emojis",
    fetcher
  );

  if (error) return "An error has occurred.";
  if (!data) return "Loading...";
  const formattedData = Object.entries(data).map((entry) => ( { emoji_name: entry[0], emoji_url: entry[1] } ));
  return (
    <div className={styles.container}>
      <Head>
        <title>Cutemoji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CuteMoji
        </h1>
        <img src={data.octopus} />
        <SearchBar apiData={formattedData} />
      </main>
    </div>
  )
}
